name: llama_cpp_dart
description: "Dart binding for llama.cpp --- high level wrappers for both Dart and Flutter"
version: 0.0.9-dev-b4586
homepage: https://github.com/rekire/llama_cpp_dart_fork

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  typed_isolate: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^16.0.0
  path_provider: ^2.1.5
  system_info2: ^4.0.0

analyzer:
  exclude:
    - 'lib/src/llama_cpp.dart'

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true