name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download test dependencies
        env:
          version: b4586
        run: |
          wget -nv https://huggingface.co/mradermacher/Oolel-Small-v0.1-GGUF/resolve/main/Oolel-Small-v0.1.Q4_K_S.gguf
          wget -nv https://github.com/ggerganov/llama.cpp/releases/download/$version/llama-$version-bin-ubuntu-x64.zip
          unzip llama-$version-bin-ubuntu-x64.zip
          rm llama-$version-bin-ubuntu-x64.zip

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2

      - name: Run tests
        run: LD_LIBRARY_PATH="$LD_LIBRARY_PATH:llama.cpp/build/bin" flutter test
