name: FFI Playground

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Checkout latest llama.cpp release
        id: llama
        run: |
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          RELEASE=`git describe --tags --abbrev=0`
          git checkout $RELEASE
          echo "version=$RELEASE" >> "$GITHUB_OUTPUT"

      - name: prepare test
        run: |
          wget https://huggingface.co/mradermacher/Oolel-Small-v0.1-GGUF/resolve/main/Oolel-Small-v0.1.Q4_K_S.gguf
          wget https://github.com/ggerganov/llama.cpp/releases/download/b4138/llama-b4138-bin-ubuntu-x64.zip
          unzip llama-b4138-bin-ubuntu-x64.zip
          mv build/bin/*.so .

      - name: run tests
        run: flutter test

      - name: Check for pending rollouts...
        id: release
        env:
          version: ${{ steps.llama.outputs.version }}
        run: |
          if git ls-remote --heads origin "rollout/$version"; then
            echo "pending=TRUE" >> "$GITHUB_OUTPUT"
          else
            echo "pending=FALSE" >> "$GITHUB_OUTPUT"
          fi

      - name: Install LLVM and Clang
        if: ${{ steps.release.outputs.pending == 'FALSE' }}
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"

      - name: Set up Flutter
        if: ${{ steps.release.outputs.pending == 'FALSE' }}
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2

      - name: run ffigen
        if: ${{ steps.release.outputs.pending == 'FALSE' }}
        id: ffigen
        env:
          version: ${{ steps.llama.outputs.version }}
        run: |
          echo -e "preamble: |\n  // AUTO GENERATED FILE by CI for release $version\n  // In order to run this locally checkout llama.cpp in this repository's root folder and run:\n  // dart run ffigen --config .github/ffigen.yaml" >> ../.github/ffigen.yaml
          dart run ffigen --config .github/ffigen.yaml
          git reset .github/ffigen.yaml
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'No changes detected.'
            echo 'diff=FALSE' >> "$GITHUB_OUTPUT"
          else
            echo 'diff=TRUE' >> "$GITHUB_OUTPUT"
          fi

      - name: Rollout changes
        if: ${{ steps.ffigen.outputs.diff == 'TRUE' }}
        env:
          version: ${{ steps.llama.outputs.version }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add lib/src/llama_cpp.dart
          git checkout -b "rollout/$version"
          git commit -m "Rollout changes of llama release $version"
          git push origin "rollout/$version"
