name: FFI Playground

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Checkout latest llama.cpp release
        id: llama
        run: |
          git clone --depth 1 https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          RELEASE=`git describe --tags --abbrev=0`
          git checkout $RELEASE
          echo "preamble: // Based on $RELEASE" >> ../.github/ffigen.yaml
          echo "version=$RELEASE" >> "$GITHUB_OUTPUT"

      - name: run ffigen
        id: ffigen
        working-directory: 'llama.cpp/include'
        env:
          VERSION: ${{ steps.llama.version }}
        run: |
          dart run ffigen --config ../../.github/ffigen.yaml
          cd ../..
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'No changes detected. See yourself:'
            git remote -v
            git status
            echo 'diff=FALSE' >> "$GITHUB_OUTPUT"
          else
            echo "Detected changes in $VERSION..."
            echo 'diff=TRUE' >> "$GITHUB_OUTPUT"
          fi

      - name: Rollout changes
        if: ${{ steps.ffigen.diff == 'TRUE' }}
        env:
          version: ${{ steps.llama.version }}
        run: |
          echo "TODO: Automate release of $version"
          git diff
